services:
  elasticsearch:
    image: elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.ml.enabled=false  # Отключаю ML, он не запускаетсявероятнее всего из-за древности процессоров
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml  # монтирование конфига
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.12.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 

  logstash:
    image: logstash:8.12.2
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        #- ./nginx_logs:/usr/share/logstash/nginx_logs
    depends_on:
      - elasticsearch
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m

  filebeat:
    image: elastic/filebeat:8.12.2
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx_logs:/var/log/nginx:ro
      - /var/log/auth.log:/var/log/auth.log:ro
    depends_on:
      - logstash

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx_logs:/var/log/nginx
    depends_on:
      - filebeat 

        
