filebeat.inputs:
- type: filestream
  paths:
    - /var/log/nginx/access.log
  fields:
    app: nginx
  processors:
    - add_host_metadata: ~

- type: filestream
  paths:
    - /var/log/auth.log
  fields:
    app: ssh
  processors:
    - add_host_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]
